### ISSUE TITLE
undefined reference to fmt while installation

### ISSUE THREAD

**Issue by intrepidChw** [shanmo/OrcVIO-Lite#1]
I tried to install the Non-ROS version, I failed at the last "make" step. The errors are:

liborcvio_estimator.so: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'
liborcvio_estimator.so: undefined reference to `fmt::v8::format_error::~format_error()'
liborcvio_estimator.so: undefined reference to `vtable for fmt::v8::format_error'
liborcvio_estimator.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
liborcvio_estimator.so: undefined reference to `fmt::v8::detail::basic_data<void>::left_padding_shifts'
liborcvio_estimator.so: undefined reference to `typeinfo for fmt::v8::format_error'
liborcvio_estimator.so: undefined reference to `fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
collect2: error: ld returned 1 exit status
CMakeFiles/orcvio.dir/build.make:175: recipe for target '../bin/orcvio' failed
make[2]: *** [../bin/orcvio] Error 1
CMakeFiles/Makefile2:982: recipe for target 'CMakeFiles/orcvio.dir/all' failed
make[1]: *** [CMakeFiles/orcvio.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Does anyone know how to solve it?

**Comment by moshanATucsd** [comment]
This is probably caused by the linking error from `eigen3` or `sophus`, try something like this as suggested [here](https://stackoverflow.com/a/59360674)
```
target_link_libraries(<target> fmt)
```

**Comment by shanmo** [comment]
You can also install fmt and set it to header only as follows 
```
git clone https://github.com/fmtlib/fmt.git
cd ./fmt
mkdir build
cmake ../
make
sudo make install
```
and add `#define FMT_HEADER_ONLY` in code where fmt is used.

**Comment by shanmo** [comment]
Note that fmt is optional, as mentioned [here](https://github.com/strasdat/Sophus)
> However, it should work (with no to minor modification) on many other modern configurations as long they support c++14, CMake, Eigen 3.3.X and (optionally) fmt. The fmt dependency can be eliminated by passing "-DUSE_BASIC_LOGGING=ON" to cmake when configuring Sophus.

**Comment by moshanATucsd** [comment]
Related issue https://github.com/strasdat/Sophus/issues/321

**Comment by moshanATucsd** [comment]
> You can also install fmt and set it to header only as follows
> 
> ```
> git clone https://github.com/fmtlib/fmt.git
> cd ./fmt
> mkdir build
> cmake ../
> make
> sudo make install
> ```
> 
> and add `#define FMT_HEADER_ONLY` in code where fmt is used.

Also need to link fmt in cmake 
![image](https://user-images.githubusercontent.com/23324577/135155238-e7ae7ca1-bdb4-4794-9448-279fe7b44044.png)

**Comment by FengQiaojun** [comment]
One solution @intrepidChw proposed, for [2.1 Non-ROS version](https://github.com/moshanATucsd/OrcVIO_Lite#21-non-ros-version), is to add `fmt::fmt-header-only` to `target_link_libraries` for `liborcvio_estimator` [here](https://github.com/moshanATucsd/OrcVIO_Lite/blob/master/CMakeLists.txt#L79) and `liborcvio_mapping` [here](https://github.com/moshanATucsd/OrcVIO_Lite/blob/master/CMakeLists.txt#L101).
That would be 
```
target_link_libraries(${PROJECT_NAME}_estimator
    ${PROJECT_NAME}_flexible_initializer
    ${SUITESPARSE_LIBRARIES}
    ${OpenCV_LIBRARIES}
    fmt::fmt-header-only
)
```
and
```
target_link_libraries(${PROJECT_NAME}_mapping
  ${OpenCV_LIBS}
  fmt::fmt-header-only)
```
Later on I will help to check the dependencies and remove unnecessary ones.

**Comment by HernandoR** [comment]
@FengQiaojun better to use 
```
#ifndef FMT_HEADER_ONLY
#define FMT_HEADER_ONLY
#endif

#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
```
