### ISSUE TITLE
python: can't open file 'scripts/convert_csv_to_txt.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by weiningwei** [shanmo/OrcVIO-Lite#2]
Hello, thank you for the open source code. But when I try to run `./run_euroc.sh PATH_TO_EUROC_DATASET/` as you mentioned, I met the error as follows:
python: can't open file 'scripts/convert_csv_to_txt.py': [Errno 2] No such file or directory
And I can't find the `scripts/convert_csv_to_txt.py` file in the folder [scripts](https://github.com/shanmo/OrcVIO-Lite/tree/master/scripts). So I think you maybe forget to upload it.

**Comment by shanmo** [comment]
Script added to `OrcVIO-Lite/scripts/convert_csv_to_txt.py`
