### ISSUE TITLE
undefined reference to `cv::hdf::open(cv::String const&)' for the tests

### ISSUE THREAD

**Issue by FengQiaojun** [shanmo/OrcVIO-Lite#3]
I had this error when compiling the [Non-ROS version](https://github.com/shanmo/OrcVIO-Lite#21-non-ros-version)

![Screenshot from 2021-09-29 12-17-06](https://user-images.githubusercontent.com/32551664/135334326-f7bae9fb-1d35-4113-9249-f77a540f75a8.png)

I am using OpenCV 3.4.14.

**Comment by shanmo** [comment]
Related [issue](https://stackoverflow.com/questions/65057812/liblibmodel-so-undefined-reference-to-cvhdfopenstdstring)
