### ISSUE TITLE
bbox

### ISSUE THREAD

**Issue by lxy-mini** [shanmo/OrcVIO-Lite#6]

**Comment by lxy-mini** [comment]
hello,I want to know how you get the data of bbox?for example,In the KITTI dataset, the vehicle pose includes position and yaw angle information. How did you get it?

**Comment by shanmo** [comment]
The measurement data only includes 2D bbox from https://github.com/shanmo/darknet-ros-wecacuee-yolov4, there is no yaw angle. The vehicle pose used in evaluation contains position and yaw, but that's from KITTI's groundtruth label, not from measurements.
